SET(ARMA_NAMES ${ARMA_NAMES} armadillo)
find_path(ARMA_INCLUDE
  NAMES ${ARMA_NAMES}
  PATHS /usr/include ${ARMA_PATHS}
  )

IF (ARMA_INCLUDE)
  SET(ARMA_INCLUDES ${ARMA_INCLUDE})
  SET(ARMA_FOUND "YES")
ELSE (ARMA_INCLUDE)
  SET(ARMA_FOUND "NO")
ENDIF (ARMA_INCLUDE)

IF (ARMA_FOUND)
   IF (NOT ARMA_FIND_QUIETLY)
      MESSAGE(STATUS "Found Armadillo: ${ARMA_INCLUDES}")
   ENDIF (NOT ARMA_FIND_QUIETLY)
ELSE (ARMA_FOUND)
   IF (ARMA_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Armadillo")
   ENDIF (ARMA_FIND_REQUIRED)
ENDIF (ARMA_FOUND)